Adding integration testing to github actions

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -64,9 +64,9 @@ jobs:
       - uses: actions/cache@v2
         with:
           path: vendor/bundle
-          key: ${{ runner.os }}-${{ matrix.puppet }}-${{ matrix.ruby }}-gems-test-${{ hashFiles('**/Gemfile.lock') }}
+          key: ${{ runner.os }}-${{ matrix.puppet }}-${{ matrix.ruby }}-gems-unit-${{ hashFiles('**/Gemfile.lock') }}
           restore-keys: |
-            ${{ runner.os }}-${{ matrix.puppet }}-${{ matrix.ruby }}-gems-test-
+            ${{ runner.os }}-${{ matrix.puppet }}-${{ matrix.ruby }}-gems-unit-
       - name: Bundle install
         run: |
           bundle install --jobs $(nproc) --retry 3
@@ -106,12 +106,71 @@ jobs:
       - name: Test
         run: 'make ${{ matrix.make_target }}'
 
-
-# TODO create a job for doing integration tests
+  integration:
+    name: '${{matrix.name}} - puppet (${{matrix.puppet}})'
+    runs-on: ubuntu-latest
+    strategy:
+      fail-fast: false
+      matrix:
+        include:
+          # note: actions/setup-ruby only allows using a major.minor release of ruby
+          - ruby: '2.5'
+            name: 'centos7-puppet5'
+          - ruby: '2.5'
+            name: 'centos7-puppet6'
+          - ruby: '2.5'
+            name: 'ubuntu16-puppet5'
+          - ruby: '2.5'
+            name: 'ubuntu16-puppet6'
+          - ruby: '2.5'
+            name: 'ubuntu18-puppet5'
+          - ruby: '2.5'
+            name: 'ubuntu18-puppet6'
+    env:
+      CHECK: '${{ matrix.check }}'
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v2
+      - name: Setup Ruby
+        uses: actions/setup-ruby@v1
+        with:
+          ruby-version: '${{ matrix.ruby }}'
+      - name: Bundle prep
+        run: |
+          gem install bundler
+          bundle -v
+          rm -f Gemfile.lock
+          # Update system gems if requested. This is useful to temporarily workaround troubles in the test runner"
+          # See https://github.com/puppetlabs/pdk-templates/commit/705154d5c437796b821691b707156e1b056d244f for an example of how this was used"
+          # Ignore exit code of SIGPIPE'd yes to not fail with shell's pipefail set"
+          [ -z "$RUBYGEMS_VERSION" ] || (yes || true) | gem update --system $RUBYGEMS_VERSION
+          gem --version
+          bundle -v
+          bundle config path vendor/bundle
+          bundle config without 'system_tests'
+          bundle lock
+        # restore cache AFTER doing 'bundle lock' so that Gemfile.lock exists
+      - uses: actions/cache@v2
+        with:
+          path: vendor/bundle
+          key: ${{ runner.os }}-${{ matrix.puppet }}-${{ matrix.ruby }}-gems-integration-${{ hashFiles('**/Gemfile.lock') }}
+          restore-keys: |
+            ${{ runner.os }}-${{ matrix.puppet }}-${{ matrix.ruby }}-gems-integration-
+      - name: Bundle install
+        run: |
+          bundle install --jobs $(nproc) --retry 3
+      - name: docker test
+        run: |
+          docker --version
+      # - name: Test
+      #   run: |
+      #     bundle exec kitchen test --debug ${{ matrix.name }}
 
   deploy:
     name: 'deploy to forge'
-    needs: unit
+    needs:
+      - unit
+      - integration
     runs-on: ubuntu-latest
     # only run deploy on tags that start with 'v'
     if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
